blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/stijnpiron/backupper/tree/main/docs
    about: Browse the project documentation
  - name: 💬 Discussions
    url: https://github.com/stijnpiron/backupper/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📊 Project Board
    url: https://github.com/stijnpiron/backupper/projects
    about: View the project roadmap and current sprint
