name: Documentation Update
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - API Documentation
        - Architecture Documentation
        - Development Guide
        - User Guide
        - Code Comments
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Document Location
      description: Which file or section needs updating?
      placeholder: "docs/ARCHITECTURE.md - Section 3.2"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Missing information
        - Incorrect information
        - Outdated information
        - Typo/Grammar
        - Unclear explanation
        - New documentation needed
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (if applicable)?
      placeholder: Copy the current text here
      render: markdown

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Change
      description: What should the documentation say instead?
      placeholder: Provide your suggested improvement
      render: markdown
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Why is this change needed? Any relevant links or references?
