name: "Generate Changelog"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to generate changelog for (e.g., v0.1.0)"
        required: false

permissions:
  contents: write
  pull-requests: read

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git diff --staged --quiet
          if [ $? -ne 0 ]; then
            git commit -m "docs: update CHANGELOG.md"
            git push
          else
            echo "No changes to CHANGELOG.md"
          fi
